version: "3.8"

services:
  mlflow:
    build:
      context: ./src
      dockerfile: Dockerfile.mlflow
    ports:
      - "5001:5001"
    volumes:
      - ./db:/db
      - ./data/artifacts:/data/artifacts
    networks:
      - app-network
  mage:
    image: mageai/mageai:latest
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env.dev
    build:
      context: .
      dockerfile: Dockerfile.mage
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
    restart: on-failure:5
    networks:
      - app-network
  # flask_app:
  #   build:
  #     context: ./src
  #     dockerfile: Dockerfile.flask
  #   ports:
  #     - "8000:5002"
  #   volumes:
  #     - ./models:/app/models
  #     - ./data/artifacts:/app/data/artifacts
  #   depends_on:
  #     - mlflow
  #   networks:
  #     - app-network
  # gradio:
  #   build:
  #     context: ./src
  #     dockerfile: Dockerfile.gradio
  #   ports:
  #     - "7860:7860"
  #   depends_on:
  #     - flask_app
  #   networks:
  #     - app-network
networks:
  app-network:
    driver: bridge
