version: "3.8"

services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5001:5001"
    volumes:
      - ./db:/db
      - ./data/artifacts:/data/artifacts
    networks:
      - app-network
  mage:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.mage
    ports:
      - 6789:6789
    volumes:
      - .hate_speech_detector/mage_data:/home/src/hate_speech_detector/mage_data
      - ./hate_speech_detector:/home/src/hate_speech_detector
      - ./data/artifacts/mlruns:/home/src/mlruns
    networks:
      - app-network
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "8000:5002"
    volumes:
      - ./models:/app/models
      - ./data/artifacts:/app/data/artifacts
    networks:
      - app-network
  # gradio:
  #   build:
  #     context: ./src
  #     dockerfile: Dockerfile.gradio
  #   ports:
  #     - "7860:7860"
  #   depends_on:
  #     - flask_app
  #   networks:
  #     - app-network
networks:
  app-network:
    driver: bridge
